# Generated by Django 6.0.6 on 2026-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('HORTALICAS', 'Hortaliças'), ('ORNAMENTAIS', 'Ornamentais')], max_length=20)),
                ('measure', models.CharField(max_length=10)),
                ('licensed', models.BooleanField()),
            ],
        ),
    ]
