# Generated by Django 6.0.6 on 2026-06-22 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='Unnamed', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('HORTALICAS', 'Hortaliças'), ('ORNAMENTAIS', 'Ornamentais')], default='Unnamed', max_length=15)),
                ('stove_name', models.CharField(blank=True, default='Unnamed', max_length=100)),
                ('date_criated', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='Product.product')),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('value_after', models.IntegerField(blank=True, default=0)),
                ('value_before', models.IntegerField(blank=True, default=0)),
                ('type_operation', models.CharField(blank=True, default='Unnamed', max_length=15)),
                ('item_stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='Stock.stockitem')),
            ],
        ),
    ]
