# Generated by Django 6.0.6 on 2026-07-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stove_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='products_licensed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='type_operation',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('REMOCAO', 'Remoção'), ('ADICAO', 'Adição')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(blank=True, default='Unnamed', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Stock.stock'),
        ),
    ]
