# Generated by Django 6.0.6 on 2026-06-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('doc_type', models.CharField(blank=True, choices=[('CPF', 'cpf'), ('CNPJ', 'cnpj')], max_length=4, null=True)),
                ('doc', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('contact', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('state_register', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_zone', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=255)),
                ('people_place', models.CharField(choices=[('RUA', 'Rua'), ('AVENIDA', 'Avenida'), ('TRAVESSA', 'Travessa'), ('ALAMEDA', 'Alameda'), ('PRACA', 'Praça'), ('ESTRADA', 'Estrada'), ('RODOVIA', 'Rodovia'), ('VIA', 'Via'), ('LARGO', 'Largo'), ('BECO', 'Beco'), ('VIELA', 'Viela'), ('SERVIDAO', 'Servidão'), ('PASSAGEM', 'Passagem'), ('QUADRA', 'Quadra'), ('CONDOMINIO', 'Condomínio'), ('CHACARA', 'Chácara'), ('SITIO', 'Sítio'), ('FAZENDA', 'Fazenda'), ('LOTEAMENTO', 'Loteamento'), ('RECANTO', 'Recanto'), ('COLONIA', 'Colônia'), ('PARQUE', 'Parque'), ('CONJUNTO', 'Conjunto')], max_length=255)),
                ('neig_b', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=8)),
                ('type', models.CharField(blank=True, choices=[('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial')], max_length=15, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client', verbose_name='client')),
            ],
        ),
    ]
